# Generated by Django 6.1.1 on 2026-09-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_note',
            field=models.CharField(blank=True, default='Shipping calculated at checkout.', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='size_guide',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
