# Generated by Django 6.1.1 on 2026-09-03 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('headline', models.CharField(max_length=160)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_href', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='banners/')),
                ('tone', models.CharField(default='paper', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='HeroChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('catalog', 'Catalog'), ('men', 'Men'), ('women', 'Women')], default='home', max_length=16)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('headline', models.CharField(max_length=160)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_href', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='heroes/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='heroes/')),
                ('overlay', models.FloatField(default=0.55)),
                ('pin_enabled', models.BooleanField(default=True)),
                ('tone', models.CharField(default='graphite', max_length=24)),
            ],
            options={
                'ordering': ['page', 'sort'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.CharField(blank=True, max_length=200)),
                ('newsletter_blurb', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='carousels/')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=160)),
                ('href', models.CharField(blank=True, max_length=200)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.carousel')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
