# Generated by Django 6.1.1 on 2026-09-03 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('phone_hours', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_note', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('address_hours', models.CharField(blank=True, max_length=80)),
                ('blurb', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'contact block',
                'verbose_name_plural': 'contact blocks',
            },
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=80)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'FAQ categories',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('popular', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.faqcategory')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
