# Generated by Django 6.1.1 on 2026-09-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_contactblock_faqcategory_faqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_flat',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_free_over',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=8),
        ),
    ]
